name: Eatery Blue Build

on:
  pull_request:
    branches: ['main', 'release']
  push:
    branches: ['main', 'release']

jobs:
  build:
    name: Build Eatery Blue Production Scheme
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download and Copy Configuration Files
        env:
          BUCKET_URL: ${{ secrets.BUCKET_URL }}
        run: |
          curl -o "${{ github.workspace }}/Eatery Blue/Supporting/Keys.xcconfig" "$BUCKET_URL/ios-secrets/eatery-blue/Keys.xcconfig"
          curl -o "${{ github.workspace }}/Eatery Blue/Supporting/GoogleService-Info.plist" "$BUCKET_URL/ios-secrets/eatery-blue/GoogleService-Info.plist"

      - name: Build
        env:
          scheme: ${{ 'Eatery Blue-Prod' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device"